# Generated by Django 6.0.7 on 2026-07-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_skills', models.JSONField(default=list)),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recommendation', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
